services:
  - type: web
    name: your-app-name # Replace with your application name
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app # Replace with your actual start command
    envVars:
      - key: PYTHON_VERSION
        value: "3.9" # Adjust as needed for your project
    buildFilter:
      paths:
        - requirements.txt
        - build.sh